#
# GENERAL {{{
#

# Index windows from 1 rather than 0
set -g base-index 1
set -g pane-base-index 1

#
# }}}
#


#
# KEYBINDS {{{
#

# Colmak-DH friendly prefix
set -g prefix C-s

# Reload conf
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Enable mouse
set -g mouse on

# Increase scroll history
set -g history-limit 3000

#
# }}}
#


#
# STYLING {{{
#

# Enable coloring
set -g default-terminal "tmux-256color"
set -ga terminal-features ",*:RGB"
setenv -g COLORTERM "truecolor"

#
# }}}
#
