[colors.bright]
black = "#928374" # gray
blue = "#076678" # dark blue
cyan = "#427B58" # dark aqua
green = "#79740E" # dark green
magenta = "#8F3F71" # dark purple
red = "#9D0006" # dark red
white = "#F2E5BC" # dark cream
yellow = "#B57614" # dark yellow

[colors.normal]
black = "#0A0A0A" # off-black
blue = "#458588" # blue
cyan = "#689D6A" # aqua
green = "#98971A" # green
magenta = "#B16286" # purple
red = "#CC241D" # red
white = "#F9F5D7" # cream
yellow = "#D79921" # yellow

[colors.primary]
background = "#F9F5D7" # cream
foreground = "#0A0A0A" # off-black

[cursor.style]
shape = "Underline"

[font]
size = 11

[font.bold]
family = "CommitMono"
style = "Bold"

[font.bold_italic]
family = "CommitMono"
style = "Bold Italic"

[font.italic]
family = "CommitMono"
style = "Italic"

[font.normal]
family = "CommitMono"
style = "Regular"

#[font.bold]
#family = "IBMPlexMono"
#style = "Bold"
#
#[font.bold_italic]
#family = "IBMPlexMono"
#style = "Bold Italic"
#
#[font.italic]
#family = "IBMPlexMono"
#style = "Italic"
#
#[font.normal]
#family = "IBMPlexMono"
#style = "Regular"

[scrolling]
history = 10000

[window]
decorations = "none"

[window.dimensions]
columns = 70
lines = 22

[window.padding]
x = 15
y = 15
